export const STANDARD_LOTS = [
  'Démolition / Dépose',
  'Gros œuvre / Maçonnerie',
  'Charpente bois',
  'Charpente métallique',
  'Couverture / Zinguerie',
  'Étanchéité',
  'Façades / Ravalement',
  "Isolation thermique par l'extérieur (ITE)",
  'Menuiseries extérieures / Vitrerie',
  'Menuiseries intérieures / Agencement',
  'Cloisons / Plâtrerie / Faux-plafonds',
  'Isolation thermique / Acoustique',
  'Carrelage / Faïence',
  'Revêtements de sols souples',
  'Parquet',
  'Peinture / Finitions',
  'Serrurerie / Métallerie',
  'Plomberie / Sanitaires',
  'Chauffage / Ventilation / Climatisation (CVC)',
  'Électricité courants forts',
  'Courants faibles / Domotique',
  'VRD / Terrassement',
  'Espaces verts / Paysagisme',
  'Cuisines / Mobilier',
  'Ascenseur / Élévateur',
  'Divers / Nettoyage',
]
