import { config } from 'dotenv'
import { resolve } from 'path'
config({ path: resolve(process.cwd(), '.env.local') })

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

const SOURCE = 'DTU/CCTP 2025'

const items: {
  lot: string
  sousLot?: string
  intitule: string
  unite?: string
}[] = [

  // ── 1. VRD / Terrassements généraux ─────────────────────────────────────
  { lot: 'VRD / Terrassements généraux', sousLot: 'Installation de chantier', intitule: 'Installation et repli de chantier — clôture, signalisation, base vie', unite: 'ens' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Installation de chantier', intitule: 'Protection des ouvrages existants (bordures, regards, candélabres)', unite: 'ens' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Terrassements', intitule: 'Décapage de terre végétale sur hauteur 20 cm, mise en dépôt', unite: 'm²' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Terrassements', intitule: 'Terrassement général en grande masse, terrain ordinaire', unite: 'm³' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Terrassements', intitule: 'Terrassement en terrain rocheux (purge et extraction)', unite: 'm³' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Terrassements', intitule: 'Fouilles en rigoles pour fondations — profondeur jusqu\'à 1,50 m', unite: 'm³' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Terrassements', intitule: 'Remblaiement et compactage par couches de 20 cm à l\'OPN', unite: 'm³' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Terrassements', intitule: 'Évacuation des déblais excédentaires en décharge agréée', unite: 'm³' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Voiries', intitule: 'Forme grave non traitée (GNT 0/31,5) — épaisseur 30 cm compacté', unite: 'm²' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Voiries', intitule: 'Couche de base grave bitume 0/14 — épaisseur 10 cm', unite: 'm²' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Voiries', intitule: 'Enrobé bitumineux BBSG 0/10 en couche de roulement — 6 cm', unite: 'm²' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Voiries', intitule: 'Bordures béton T2 posées sur béton de pose, joints', unite: 'ml' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Voiries', intitule: 'Caniveau béton C1 préfabriqué avec grille fonte — classe D400', unite: 'ml' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Réseaux EP', intitule: 'Tranchée pour réseau eaux pluviales, fouille et remblai', unite: 'ml' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Réseaux EP', intitule: 'Canalisation PVC CR8 Ø200 pour eaux pluviales, pose en tranchée', unite: 'ml' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Réseaux EP', intitule: 'Regard de visite béton préfabriqué 1000×1000, avec cadre et tampon fonte', unite: 'u' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Réseaux EP', intitule: 'Regard avaloir siphoïde avec grille fonte — classe C250', unite: 'u' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Réseaux EU/EV', intitule: 'Canalisation PVC CR8 Ø160 eaux usées, pose en tranchée avec lit de sable', unite: 'ml' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Réseaux EU/EV', intitule: 'Regard de branchement eaux usées Ø315, avec tampon fonte', unite: 'u' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Réseaux divers', intitule: 'Fourreau TPC Ø90 pour réseaux électriques/télécom en tranchée', unite: 'ml' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Réseaux divers', intitule: 'Grillage avertisseur (rouge électricité / vert télécom / jaune gaz)', unite: 'ml' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Réseaux divers', intitule: 'Raccordement au réseau public d\'assainissement — branchement complet', unite: 'u' },
  { lot: 'VRD / Terrassements généraux', sousLot: 'Espaces stabilisés', intitule: 'Stabilisé gravillonné roulé (calcaire 10/14) sur géotextile — e=15 cm', unite: 'm²' },

  // ── 2. Fondations / Gros œuvre ──────────────────────────────────────────
  { lot: 'Fondations / Gros œuvre', sousLot: 'Fondations', intitule: 'Semelles filantes béton armé — C25/30, aciers HA, largeur 60 cm', unite: 'ml' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Fondations', intitule: 'Semelles isolées béton armé — C25/30 sous poteaux', unite: 'u' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Fondations', intitule: 'Béton de propreté dosé à 150 kg/m³ — épaisseur 10 cm', unite: 'm²' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Fondations', intitule: 'Pieux forés béton armé Ø400, y compris têtes de pieux', unite: 'ml' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Fondations', intitule: 'Drainage périphérique des fondations — géotextile + drain Ø100 + gravier', unite: 'ml' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Infrastructure', intitule: 'Voile béton armé sous-sol e=20 cm — C25/30, coffrage deux faces', unite: 'm²' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Infrastructure', intitule: 'Cuvelage intérieur par membrane drainante + enduit d\'imperméabilisation', unite: 'm²' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Infrastructure', intitule: 'Dallage béton armé sur terre-plein — C25/30, e=15 cm, treillis soudé', unite: 'm²' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Infrastructure', intitule: 'Vide sanitaire — parpaings porteurs + hourdis béton + forme de pente', unite: 'm²' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Élévations', intitule: 'Mur en maçonnerie de blocs béton 20 cm — moyen creux, mortier M10', unite: 'm²' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Élévations', intitule: 'Mur en béton banché armé e=20 cm — C25/30, coffrage métallique', unite: 'm²' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Élévations', intitule: 'Poteau béton armé section 30×30 cm — C25/30, aciers filants', unite: 'ml' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Élévations', intitule: 'Poutre béton armé section 30×50 cm — C25/30, coffrage bois perdu', unite: 'ml' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Planchers', intitule: 'Plancher à corps creux (hourdis + poutrelles) — surcharge 250 kg/m²', unite: 'm²' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Planchers', intitule: 'Dalle pleine béton armé e=20 cm — C25/30, coffrage bois', unite: 'm²' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Planchers', intitule: 'Escalier béton armé (paillasse + limons) — coffrage, ferraillage, décoffrage', unite: 'u' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Divers GO', intitule: 'Linteau béton armé préfabriqué — différentes portées jusqu\'à 2,50 m', unite: 'ml' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Divers GO', intitule: 'Chaînage horizontal périphérique — béton armé 20×20 cm', unite: 'ml' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Divers GO', intitule: 'Réservations et calfeutrements pour passages de réseaux', unite: 'ens' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Divers GO', intitule: 'Acrotère béton armé — h=50 cm, coffrage deux faces', unite: 'ml' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Divers GO', intitule: 'Enduit de façade rustique tyrolien 2 couches sur béton / parpaing', unite: 'm²' },
  { lot: 'Fondations / Gros œuvre', sousLot: 'Divers GO', intitule: 'Scellements et calfeutrements divers — fourreaux, boîtiers, cornières', unite: 'ens' },

  // ── 3. Charpente bois ────────────────────────────────────────────────────
  { lot: 'Charpente bois', sousLot: 'Charpente traditionnelle', intitule: 'Fermette industrielle en sapin C24 — portée jusqu\'à 10 m, entre-axe 60 cm', unite: 'u' },
  { lot: 'Charpente bois', sousLot: 'Charpente traditionnelle', intitule: 'Arbalétrier en chêne ou sapin — section 8×16 cm', unite: 'ml' },
  { lot: 'Charpente bois', sousLot: 'Charpente traditionnelle', intitule: 'Panne faîtière en sapin — section 8×16 cm, traitement classe 2', unite: 'ml' },
  { lot: 'Charpente bois', sousLot: 'Charpente traditionnelle', intitule: 'Pannes intermédiaires et de rive — section 6×12 cm', unite: 'ml' },
  { lot: 'Charpente bois', sousLot: 'Charpente traditionnelle', intitule: 'Chevrons en sapin — section 6×8 cm, espacement 50 cm', unite: 'ml' },
  { lot: 'Charpente bois', sousLot: 'Charpente traditionnelle', intitule: 'Voliges bois brut — épaisseur 22 mm, clouées sur chevrons', unite: 'm²' },
  { lot: 'Charpente bois', sousLot: 'Charpente traditionnelle', intitule: 'Contreventement triangulé — croix de Saint-André, section 4×8 cm', unite: 'ens' },
  { lot: 'Charpente bois', sousLot: 'Charpente lamellé-collé', intitule: 'Poutre lamellé-collé GL24h — portée jusqu\'à 12 m, section variable', unite: 'ml' },
  { lot: 'Charpente bois', sousLot: 'Charpente lamellé-collé', intitule: 'Poteau lamellé-collé section 18×18 cm — y compris platines de pied', unite: 'ml' },
  { lot: 'Charpente bois', sousLot: 'Charpente lamellé-collé', intitule: 'Arche lamellé-collé — portée 15 m, flèche 3 m, section courbe', unite: 'u' },
  { lot: 'Charpente bois', sousLot: 'CLT / Bois massif', intitule: 'Panneaux CLT 5 plis — épaisseur 100 mm, plancher bois massif', unite: 'm²' },
  { lot: 'Charpente bois', sousLot: 'CLT / Bois massif', intitule: 'Panneaux CLT 3 plis — épaisseur 80 mm, mur porteur', unite: 'm²' },
  { lot: 'Charpente bois', sousLot: 'Ossature bois', intitule: 'Ossature bois en poteaux/poutres — section 45×145 mm, entraxe 60 cm', unite: 'm²' },
  { lot: 'Charpente bois', sousLot: 'Ossature bois', intitule: 'Lisse basse et sablière haute — section 45×145 mm sur seuil alu', unite: 'ml' },
  { lot: 'Charpente bois', sousLot: 'Ossature bois', intitule: 'Habillage extérieur OSB3 — épaisseur 12 mm, agrafé sur ossature', unite: 'm²' },
  { lot: 'Charpente bois', sousLot: 'Assemblages', intitule: 'Connecteurs métalliques galvanisés — équerres, sabots, boulons M12', unite: 'ens' },
  { lot: 'Charpente bois', sousLot: 'Assemblages', intitule: 'Traitement préventif fongicide/insecticide — classe d\'emploi 2', unite: 'm²' },
  { lot: 'Charpente bois', sousLot: 'Trappe et accès', intitule: 'Trappe d\'accès combles 60×80 cm — cadre bois, échelle escamotable', unite: 'u' },
  { lot: 'Charpente bois', sousLot: 'Trappe et accès', intitule: 'Puits de lumière sur charpente — 78×118 cm, double vitrage', unite: 'u' },
  { lot: 'Charpente bois', sousLot: 'Trappe et accès', intitule: 'Fenêtre de toit type Velux — 78×118 cm, GGL tout confort', unite: 'u' },
  { lot: 'Charpente bois', sousLot: 'Trappe et accès', intitule: 'Fourrure et lattage pour support de couverture — section 27×40 mm', unite: 'm²' },

  // ── 4. Charpente métallique ──────────────────────────────────────────────
  { lot: 'Charpente métallique', sousLot: 'Structure principale', intitule: 'Poteaux en profilé HEA 160 — acier S235, avec platines de pied boulonnées', unite: 'ml' },
  { lot: 'Charpente métallique', sousLot: 'Structure principale', intitule: 'Poutres IPE 200 — acier S235, assemblage par soudure ou boulonnage', unite: 'ml' },
  { lot: 'Charpente métallique', sousLot: 'Structure principale', intitule: 'Poutres treillis tubulaires — portée 12 m, acier S355 galvanisé', unite: 'u' },
  { lot: 'Charpente métallique', sousLot: 'Structure principale', intitule: 'Portique métallique — travée 15 m, faîtage 6 m, acier S355 laqué', unite: 'u' },
  { lot: 'Charpente métallique', sousLot: 'Secondaire / Contreventement', intitule: 'Pannes Z140 — acier galvanisé, entraxe 1,50 m, fixées sur poteaux', unite: 'ml' },
  { lot: 'Charpente métallique', sousLot: 'Secondaire / Contreventement', intitule: 'Croix de contreventement en cornières L50×5 — boulonnées', unite: 'ens' },
  { lot: 'Charpente métallique', sousLot: 'Secondaire / Contreventement', intitule: 'Lisses de bardage en U 80×40 — galvanisées, entraxe 1,80 m', unite: 'ml' },
  { lot: 'Charpente métallique', sousLot: 'Planchers métalliques', intitule: 'Bac acier collaborant (plancher mixte) — épaisseur 75/0,75 + béton e=12 cm', unite: 'm²' },
  { lot: 'Charpente métallique', sousLot: 'Planchers métalliques', intitule: 'Connecteurs cisaillement — goujons Nelson Ø19, soudés sur IPE', unite: 'u' },
  { lot: 'Charpente métallique', sousLot: 'Planchers métalliques', intitule: 'Dalle sur bac acier — béton C25/30, treillis soudé ST25, e=8 cm', unite: 'm²' },
  { lot: 'Charpente métallique', sousLot: 'Traitements de surface', intitule: 'Sablage Sa2,5 + primaire époxy 60 µm sur charpente acier', unite: 'm²' },
  { lot: 'Charpente métallique', sousLot: 'Traitements de surface', intitule: 'Peinture polyuréthane 2 couches RAL au choix — finition brillante', unite: 'm²' },
  { lot: 'Charpente métallique', sousLot: 'Traitements de surface', intitule: 'Galvanisation à chaud — pièces diverses zinguées à 85 µm min.', unite: 'kg' },
  { lot: 'Charpente métallique', sousLot: 'Traitements de surface', intitule: 'Protection feu 60 min — peinture intumescente sur acier nu', unite: 'm²' },
  { lot: 'Charpente métallique', sousLot: 'Assemblages et ancrages', intitule: 'Platine d\'ancrage 300×300×20 mm — avec tiges fileté M20 scellées', unite: 'u' },
  { lot: 'Charpente métallique', sousLot: 'Assemblages et ancrages', intitule: 'Boulons HR 10.9 M16 — assemblage haute résistance avec rondelles', unite: 'ens' },
  { lot: 'Charpente métallique', sousLot: 'Divers métallerie', intitule: 'Garde-corps acier laqué h=1,10 m — tube carré 40×40 + remplissage verre', unite: 'ml' },
  { lot: 'Charpente métallique', sousLot: 'Divers métallerie', intitule: 'Escalier droit métallique — limon tôle, marches caillebotis, rampe tubulaire', unite: 'u' },
  { lot: 'Charpente métallique', sousLot: 'Divers métallerie', intitule: 'Mezzanine métallique — surface 30 m², structure IPE 160 + plancher bois', unite: 'ens' },
  { lot: 'Charpente métallique', sousLot: 'Divers métallerie', intitule: 'Chéneau en tôle d\'acier galvanisé développé 500 mm, y compris descentes', unite: 'ml' },

  // ── 5. Couverture / Étanchéité ───────────────────────────────────────────
  { lot: 'Couverture / Étanchéité', sousLot: 'Tuiles et ardoises', intitule: 'Couverture en tuiles plates terre cuite 10 cm — pose sur voligeage', unite: 'm²' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Tuiles et ardoises', intitule: 'Couverture en tuiles mécaniques à emboîtement — pente min. 35%', unite: 'm²' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Tuiles et ardoises', intitule: 'Ardoises naturelles d\'Angers 32×22 cm — pose sur voligeage bois', unite: 'm²' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Tuiles et ardoises', intitule: 'Ardoises fibrociment 40×24 cm — imitation naturelle, fixation inox', unite: 'm²' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Zinc / Bac acier', intitule: 'Couverture bac acier laqué — nervures 40 mm, pose par emboîtement, ep. 0,75', unite: 'm²' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Zinc / Bac acier', intitule: 'Couverture à joint debout en zinc naturel — feuilles 0,65 mm, à tasseaux', unite: 'm²' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Zinc / Bac acier', intitule: 'Noue en zinc naturel — développé 500 mm, soudée sur platelage bois', unite: 'ml' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Faîtages et rives', intitule: 'Faîtage en tuile de rive — avec mortier de jointoiement hybride', unite: 'ml' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Faîtages et rives', intitule: 'Rive en tuile de rive ou bande de rive zinc — y compris etanchéité', unite: 'ml' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Étanchéité toiture terrasse', intitule: 'Étanchéité bicouche SBS sur toiture terrasse — sous protection lourde', unite: 'm²' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Étanchéité toiture terrasse', intitule: 'Étanchéité monocouche TPO 1,5 mm — soudée à l\'air chaud, fixation mécanique', unite: 'm²' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Étanchéité toiture terrasse', intitule: 'Toiture végétalisée extensive — substrat 8 cm + plantes sédum', unite: 'm²' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Étanchéité toiture terrasse', intitule: 'Relevés d\'étanchéité sur acrotère h=40 cm — membrane SBS + solin', unite: 'ml' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Évacuations pluviales', intitule: 'Chéneau pendulaire zinc développé 400 mm — fixation sur liteau', unite: 'ml' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Évacuations pluviales', intitule: 'Descente EP en zinc Ø100 — bagues de fixation tous les 2 m', unite: 'ml' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Évacuations pluviales', intitule: 'Entonnoir de descente EP en zinc — y compris coudes de raccordement', unite: 'u' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Accessoires couverture', intitule: 'Châssis de désenfumage NF S61-937 — 1 m², ventilation naturelle', unite: 'u' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Accessoires couverture', intitule: 'Crochet à neige galvanisé — pose sur tuile de couverture', unite: 'u' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Accessoires couverture', intitule: 'Écran sous toiture HPV — 3 couches, pose entre chevrons', unite: 'm²' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Accessoires couverture', intitule: 'Grille anti-oiseaux pour entrée d\'air en soffite — acier galvanisé', unite: 'ml' },
  { lot: 'Couverture / Étanchéité', sousLot: 'Accessoires couverture', intitule: 'Solin en zinc ou plomb — jonction couverture/façade, développé 250 mm', unite: 'ml' },

  // ── 6. Ravalement / Façades ──────────────────────────────────────────────
  { lot: 'Ravalement / Façades', sousLot: 'Préparation des supports', intitule: 'Nettoyage haute pression (150 bars) des façades existantes', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'Préparation des supports', intitule: 'Piquage des enduits défectueux et ragréage des épaufrures', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'Préparation des supports', intitule: 'Traitement anti-mousse / anti-champignons biocide', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'Enduits façade', intitule: 'Enduit de ravalement minéral gratté fin — épaisseur 10 mm, 2 couches', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'Enduits façade', intitule: 'Enduit projeté à la taloche (tyrolien) — finition rustique', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'Enduits façade', intitule: 'Peinture façade acrylique siloxane — 2 couches sur fond existant sain', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'ITE (Isolation Thermique Extérieure)', intitule: 'ITE polystyrène expansé graphité 100 mm — collé + chevilles, finition enduit', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'ITE (Isolation Thermique Extérieure)', intitule: 'ITE laine de roche 120 mm — sous enduit mince sur treillis fibres de verre', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'ITE (Isolation Thermique Extérieure)', intitule: 'Sous-enduit d\'accrochage avec treillis armé — 10×10 mm, maille 160 g/m²', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'ITE (Isolation Thermique Extérieure)', intitule: 'Enduit de finition silicone grainé fin sur ITE — couleur au choix', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'Bardage', intitule: 'Bardage bois massif douglas — lames 21×145 mm, fixation inox, lasure', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'Bardage', intitule: 'Bardage composite fibres-ciment — planches 8 mm, fixation invisible', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'Bardage', intitule: 'Bardage aluminium laqué — cassettes 200×600 mm, RAL au choix', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'Bardage', intitule: 'Ossature bois verticale pour bardage — section 45×70 mm, lame d\'air 2 cm', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'Accessoires façade', intitule: 'Profil de départ ITE — aluminium laqué, avec goutte d\'eau', unite: 'ml' },
  { lot: 'Ravalement / Façades', sousLot: 'Accessoires façade', intitule: 'Tableau, appui et linteau de baie en enduit — finition soignée', unite: 'u' },
  { lot: 'Ravalement / Façades', sousLot: 'Accessoires façade', intitule: 'Appui de fenêtre en pierre reconstituée — largeur 35 cm, profil larmier', unite: 'ml' },
  { lot: 'Ravalement / Façades', sousLot: 'Accessoires façade', intitule: 'Joint de fractionnement PVC — tous les 30 m² d\'enduit façade', unite: 'ml' },
  { lot: 'Ravalement / Façades', sousLot: 'Échafaudage', intitule: 'Location et montage d\'échafaudage de façade — pour durée chantier', unite: 'm²' },
  { lot: 'Ravalement / Façades', sousLot: 'Échafaudage', intitule: 'Bâche de protection chantier sur échafaudage — pare-pluie et anti-projection', unite: 'm²' },

  // ── 7. Menuiseries extérieures ───────────────────────────────────────────
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Fenêtres', intitule: 'Fenêtre aluminium 2 vantaux ouverture à la française — DV 4/16/4 Ar, Uw≤1,0', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Fenêtres', intitule: 'Fenêtre PVC 2 vantaux oscillo-battant — DV argon 4/16/4, Uw≤1,1', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Fenêtres', intitule: 'Fenêtre bois lamellé-collé pin — DV 4/16/4, peint blanc, quincaillerie inox', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Fenêtres', intitule: 'Fenêtre fixe aluminium grand format — DV 6/16/4 Ar feuilleté, Uw≤1,0', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Baies vitrées / Coulissants', intitule: 'Baie coulissante aluminium 2 vantaux — DV 4/16/4 Ar, 2400×2200 mm', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Baies vitrées / Coulissants', intitule: 'Galandage aluminium — vantail coulissant dans paroi, galet Inox', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Baies vitrées / Coulissants', intitule: 'Verrière de toiture aluminium — châssis fixe avec double vitrage feuilleté', unite: 'm²' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Portes extérieures', intitule: 'Porte d\'entrée aluminium thermique — 1 vantail, vitrage sécurité, serrure A2P', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Portes extérieures', intitule: 'Porte d\'entrée bois chêne — 1 vantail massif, triple vitrage, laquée', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Portes extérieures', intitule: 'Porte de service acier galvanisé + panneau isolant e=40 mm — EI30', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Volets / Occultants', intitule: 'Volet roulant aluminium motorisé — coffre tunnel, lame 55 mm, radio', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Volets / Occultants', intitule: 'Volet battant aluminium — lames orientables, couleur RAL au choix', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Volets / Occultants', intitule: 'Store banne motorisé extérieur — toile acrylique 350 cm, bras articulés', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Accessoires', intitule: 'Seuil de porte aluminium laqué avec joint brosse — longueur au ml', unite: 'ml' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Accessoires', intitule: 'Grille de ventilation en tableau de baie — aluminium anodisé, réglable', unite: 'u' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Accessoires', intitule: 'Joint de calfeutrement périphérique des menuiseries — mousse précomprimée', unite: 'ml' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Accessoires', intitule: 'Film solaire ou décoratif collé sur vitrage — transmission 40%', unite: 'm²' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Accessoires', intitule: 'Motorisation volet roulant et domotique — group commande centrale', unite: 'ens' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Mur rideau', intitule: 'Mur rideau aluminium ossature — montants 60 mm, DV 6/16/4 feuilleté', unite: 'm²' },
  { lot: 'Menuiseries extérieures (aluminium / PVC / bois)', sousLot: 'Mur rideau', intitule: 'Imposte fixe au-dessus menuiserie — aluminium, vitrage clair', unite: 'u' },

  // ── 8. Serrurerie / Métallerie ───────────────────────────────────────────
  { lot: 'Serrurerie / Métallerie', sousLot: 'Garde-corps', intitule: 'Garde-corps acier laqué h=1,10 m — main courante tube Ø42, barreaux plats', unite: 'ml' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Garde-corps', intitule: 'Garde-corps inox brossé h=1,10 m — câbles Ø8 mm tendus, poteaux carrés', unite: 'ml' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Garde-corps', intitule: 'Garde-corps vitré feuilleté 10/10 — fixation par pinces inox, h=1,10 m', unite: 'ml' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Escaliers', intitule: 'Escalier droit acier laqué — limon tôle 10 mm, marches métal déployé', unite: 'u' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Escaliers', intitule: 'Escalier hélicoïdal acier — Ø130 cm, marches fonte, main courante ronde', unite: 'u' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Escaliers', intitule: 'Main courante acier laqué — tube Ø42×2 mm sur potelets à sceller', unite: 'ml' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Portails et clôtures', intitule: 'Portail battant acier galvanisé laqué — 2 vantaux 2×1,50 m, motorisé', unite: 'u' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Portails et clôtures', intitule: 'Portillon piéton acier laqué — 1 m, ferme-porte, serrure 3 points', unite: 'u' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Portails et clôtures', intitule: 'Clôture grillage soudé galvanisé H=1,50 m — mailles 50×50 mm', unite: 'ml' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Portails et clôtures', intitule: 'Clôture panneaux rigides laqués — lames horizontales, poteaux scellés', unite: 'ml' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Trappes et traitement de surface', intitule: 'Trappe de visite en plancher — cadre + panneau acier laqué, charnières', unite: 'u' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Trappes et traitement de surface', intitule: 'Peinture époxy 2K sur ouvrages métalliques — après sablage SA2,5', unite: 'm²' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Divers serrurerie', intitule: 'Grille de protection fenêtre rez-de-chaussée — barreaux Ø12, inox', unite: 'u' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Divers serrurerie', intitule: 'Caillebotis galvanisé — maille 30×30 mm, ep.25 mm, sur cadre', unite: 'm²' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Divers serrurerie', intitule: 'Traitement galvanisation à chaud — immersion à 450°C, protection 40+ ans', unite: 'kg' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Divers serrurerie', intitule: 'Nez de marche antidérapant aluminium laqué — pose collée sur escalier', unite: 'ml' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Divers serrurerie', intitule: 'Plaque de propreté inox brossé — format 200×50 mm, vissée', unite: 'u' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Divers serrurerie', intitule: 'Barre anti-panique sur porte coupe-feu — type PANIC BAR NF EN 1125', unite: 'u' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Divers serrurerie', intitule: 'Tôle déployée acier galvanisé — 20×8 mm, clôture ou grillage décoratif', unite: 'm²' },
  { lot: 'Serrurerie / Métallerie', sousLot: 'Divers serrurerie', intitule: 'Cornière de protection angle mur — cornière PVC 2,5 m ou acier laqué', unite: 'u' },

  // ── 9. Menuiseries intérieures ───────────────────────────────────────────
  { lot: 'Menuiseries intérieures', sousLot: 'Portes intérieures', intitule: 'Bloc-porte isoplane pleine 83×204 cm — finition laquée blanc, huisserie acier', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Portes intérieures', intitule: 'Bloc-porte vitrée — vantail avec vitre givré 30×90 cm, cadre bois peint', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Portes intérieures', intitule: 'Porte coulissante en applique — rail apparent alu, vantail 93 cm, peint', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Portes intérieures', intitule: 'Porte coulissante galandage — vantail en bois laqué 83 cm, rail encastré', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Portes intérieures', intitule: 'Porte coupe-feu EI30 — bloc-porte acier, joint intumescent, ferme-porte', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Portes intérieures', intitule: 'Porte tambour acoustique Rw=42 dB — huisserie pré-humidifiée, joint périmétral', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Placards et rangements', intitule: 'Placard à deux vantaux battants — structure MDF peint, tablettes réglables', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Placards et rangements', intitule: 'Placard coulissant sur rail — 2 vantaux miroir + bois laqué, h=2,50 m', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Placards et rangements', intitule: 'Penderie sur mesure en MDF laqué — tringle, tiroirs, tablettes réglables', unite: 'ens' },
  { lot: 'Menuiseries intérieures', sousLot: 'Habillages bois', intitule: 'Bardage intérieur bois peuplier — lames 135 mm, pose à joints couverts', unite: 'm²' },
  { lot: 'Menuiseries intérieures', sousLot: 'Habillages bois', intitule: 'Lambris PVC blanc — pose sur tasseaux, longueur 4 ml, raccords', unite: 'm²' },
  { lot: 'Menuiseries intérieures', sousLot: 'Habillages bois', intitule: 'Boiserie de fenêtre — tableau, ébrasement et appui en MDF peint', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Plinthes et finitions', intitule: 'Plinthe MDF peint — h=100 mm, posée collée ou clouée', unite: 'ml' },
  { lot: 'Menuiseries intérieures', sousLot: 'Plinthes et finitions', intitule: 'Quart-de-rond MDF peint — r=25 mm, jonction sol/plinthe', unite: 'ml' },
  { lot: 'Menuiseries intérieures', sousLot: 'Plinthes et finitions', intitule: 'Cache-fil bois peint — 3 compartiments, 60×20 mm, pose collée', unite: 'ml' },
  { lot: 'Menuiseries intérieures', sousLot: 'Quincaillerie', intitule: 'Serrure à encastrer 3 points — cylindre européen + 3 clés', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Quincaillerie', intitule: 'Poignée de porte inox brossé — modèle carré ou rond, rosace et gâche', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Quincaillerie', intitule: 'Ferme-porte hydraulique réglable EN 3 — montage en applique', unite: 'u' },
  { lot: 'Menuiseries intérieures', sousLot: 'Quincaillerie', intitule: 'Paumelles soudées inox Ø14 — jeu de 3 par vantail', unite: 'jeu' },
  { lot: 'Menuiseries intérieures', sousLot: 'Quincaillerie', intitule: 'Butée de porte murale ou sol — inox, avec amortisseur caoutchouc', unite: 'u' },

  // ── 10. Cloisons / Doublages ─────────────────────────────────────────────
  { lot: 'Cloisons / Doublages', sousLot: 'Cloisons légères', intitule: 'Cloison distributive 72/48 — simple plaque BA13 chaque face, e=98 mm', unite: 'm²' },
  { lot: 'Cloisons / Doublages', sousLot: 'Cloisons légères', intitule: 'Cloison distributive 72/48 acoustique — double plaque BA13 chaque face, e=120 mm', unite: 'm²' },
  { lot: 'Cloisons / Doublages', sousLot: 'Cloisons légères', intitule: 'Cloison hydrofuge BA18 en zone humide — plaque GKBI chaque face', unite: 'm²' },
  { lot: 'Cloisons / Doublages', sousLot: 'Cloisons légères', intitule: 'Cloison de séparation haute performance Rw=52 dB — ossature décollée', unite: 'm²' },
  { lot: 'Cloisons / Doublages', sousLot: 'Cloisons légères', intitule: 'Cloison en bloc de béton cellulaire 10 cm (Siporex) — collée à la colle', unite: 'm²' },
  { lot: 'Cloisons / Doublages', sousLot: 'Doublages intérieurs', intitule: 'Doublage collé PSE 40 mm + BA13 — sur mur maçonné, joint périphérique', unite: 'm²' },
  { lot: 'Cloisons / Doublages', sousLot: 'Doublages intérieurs', intitule: 'Doublage sur ossature — laine de roche 45 mm + BA13 — e=63 mm', unite: 'm²' },
  { lot: 'Cloisons / Doublages', sousLot: 'Doublages intérieurs', intitule: 'Contre-cloison de doublage 50/50 — sur mur extérieur, laine minérale', unite: 'm²' },
  { lot: 'Cloisons / Doublages', sousLot: 'Doublages intérieurs', intitule: 'Doublage en plaque de liège — e=30 mm, collé sur plâtre ou béton', unite: 'm²' },
  { lot: 'Cloisons / Doublages', sousLot: 'Habillages plaque', intitule: 'Habillage poteaux béton en plaque BA13 — ossature métal, finition peint', unite: 'u' },
  { lot: 'Cloisons / Doublages', sousLot: 'Habillages plaque', intitule: 'Gaine technique en plaque BA13 — section 300×300 mm, accès par trappe', unite: 'ml' },
  { lot: 'Cloisons / Doublages', sousLot: 'Joints et finitions', intitule: 'Bande de joint armé sur raccords cloison — bande à enduire + enduit plâtre', unite: 'ml' },
  { lot: 'Cloisons / Doublages', sousLot: 'Joints et finitions', intitule: 'Cornière d\'angle PVC ou métal sur arêtes vives cloison', unite: 'ml' },
  { lot: 'Cloisons / Doublages', sousLot: 'Joints et finitions', intitule: 'Joint acoustique périphérique — silicone souple à la base des cloisons', unite: 'ml' },
  { lot: 'Cloisons / Doublages', sousLot: 'Cloisons amovibles', intitule: 'Cloison amovible démontable — panneaux 100 cm, hauteur 2,80 m, phonique', unite: 'm²' },
  { lot: 'Cloisons / Doublages', sousLot: 'Cloisons amovibles', intitule: 'Cloison vitrée sur cadre aluminium — double vitrage 4/12/4, h=2,80 m', unite: 'm²' },
  { lot: 'Cloisons / Doublages', sousLot: 'Cloisons amovibles', intitule: 'Porte vitrée dans cloison aluminium — vantail 83 cm, poignée inox', unite: 'u' },
  { lot: 'Cloisons / Doublages', sousLot: 'Divers', intitule: 'Encadrement de baie en cloison — montant double renforcé + linteau', unite: 'u' },
  { lot: 'Cloisons / Doublages', sousLot: 'Divers', intitule: 'Réservation pour passage de réseaux en cloison — collier coupe-feu si nécessaire', unite: 'u' },
  { lot: 'Cloisons / Doublages', sousLot: 'Divers', intitule: 'Appui de fenêtre en plaque BA13 — tablette 25 cm + finition enduit', unite: 'u' },

  // ── 11. Plâtrerie / Faux-plafonds ────────────────────────────────────────
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Enduits plâtre', intitule: 'Enduit plâtre traditionnel 2 couches sur maçonnerie — épaisseur 15 mm', unite: 'm²' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Enduits plâtre', intitule: 'Gobetis d\'accrochage sur béton — gypsum projeté, e=5 mm', unite: 'm²' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Enduits plâtre', intitule: 'Enduit de lissage fin — finition Q4 prête à peindre, e=1 mm', unite: 'm²' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Enduits plâtre', intitule: 'Enduit hydrofuge en zone humide — type Weber plaquevite H', unite: 'm²' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Enduits plâtre', intitule: 'Corniche en plâtre moulée — modèle classique H=100 mm, posée collée', unite: 'ml' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Faux-plafonds suspendus', intitule: 'Faux-plafond démontable dalles 60×60 Rockfon — ossature T24 apparent', unite: 'm²' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Faux-plafonds suspendus', intitule: 'Faux-plafond plaque BA13 sur ossature — y compris joints et enduits', unite: 'm²' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Faux-plafonds suspendus', intitule: 'Faux-plafond coupe-feu EI60 — plaque Fireboard 15 mm sur ossature', unite: 'm²' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Faux-plafonds suspendus', intitule: 'Faux-plafond acoustique — laine de verre 80 mm au-dessus, dalle Écophon', unite: 'm²' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Faux-plafonds suspendus', intitule: 'Faux-plafond en plâtre BA18 en zone humide (salle de bain)', unite: 'm²' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Faux-plafonds en staff', intitule: 'Voûte en staff — préfabriquée en atelier, pose et scellement en place', unite: 'm²' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Faux-plafonds en staff', intitule: 'Rosace en staff — modèle au choix Ø50 cm, posée et jointoyée', unite: 'u' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Faux-plafonds en staff', intitule: 'Staff de corniche moulée — section 120×120 mm, posée par tirants', unite: 'ml' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Caissons et niches', intitule: 'Caisson lumineux en BA13 — pour dalle LED encastrée, finition lissée', unite: 'ml' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Caissons et niches', intitule: 'Niche décorative encastrée en cloison — BA13, fond carrelé ou peint', unite: 'u' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Caissons et niches', intitule: 'Habillage trémie d\'escalier en BA13 — finition enduit peinture', unite: 'ens' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Accessoires', intitule: 'Trappe de visite plafond en BA13 — 300×300 mm, charnières, verrouillage', unite: 'u' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Accessoires', intitule: 'Réservation pour luminaire encastré dans faux-plafond — diamètre au choix', unite: 'u' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Accessoires', intitule: 'Joint de fractionnement en faux-plafond — profil alu anodisé H', unite: 'ml' },
  { lot: 'Plâtrerie / Faux-plafonds', sousLot: 'Accessoires', intitule: 'Ragréage de sol autolissant — pour rattrapage planéité avant carrelage', unite: 'm²' },

  // ── 12. Isolation thermique et acoustique ────────────────────────────────
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation combles', intitule: 'Soufflage laine de verre en combles perdus — R=7 m².K/W, e=220 mm', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation combles', intitule: 'Rouleaux laine de roche 200 mm entre chevrons — R=5,5 m².K/W', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation combles', intitule: 'Sarking polyuréthane 120 mm sous couverture — R=5,5 m².K/W, λ=0,022', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation combles', intitule: 'Pare-vapeur kraft 220 g/m² — posé sous isolation, jonctions scotchées', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation plancher', intitule: 'Isolation plancher bas laine de roche 100 mm — R=2,65 m².K/W', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation plancher', intitule: 'Isolation sous chape PSE 50 mm — R=1,45 m².K/W, anti-vibratile', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation plancher', intitule: 'Chape sèche (double plaque Fermacell) — sur plots résilients, e=35 mm', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation plancher', intitule: 'Résilient acoustique sous chape — 10 mm, Rw amélioration +20 dB', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation murs', intitule: 'Laine de roche 100 mm en ossature cloison — R=2,65 m².K/W', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation murs', intitule: 'Mousse polyuréthane projetée 80 mm sur mur — adhérence directe, R=3,6', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation murs', intitule: 'Ouate de cellulose soufflée en mur ossature bois — R=4 m².K/W, e=140 mm', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Isolation murs', intitule: 'Panneau rigide PIR 80 mm sur plancher chauffant — λ=0,022, R=3,6', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Acoustique', intitule: 'Plots antivibratiles sous équipements techniques — lot de 4 par machine', unite: 'jeu' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Acoustique', intitule: 'Silencieux sur gaine ventilation — atténuation 15 dB, L=60 cm', unite: 'u' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Acoustique', intitule: 'Manchon acoustique souple sur tuyauterie — isolant 25 mm, armé', unite: 'ml' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Acoustique', intitule: 'Panneaux acoustiques muraux — laine de roche 40 mm, habillage tissu', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Acoustique', intitule: 'Mesure acoustique en réception — test conformité NRA, rapport écrit', unite: 'ens' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Étanchéité à l\'air', intitule: 'Membrane d\'étanchéité à l\'air Sd=200 m — jonctions adhésif double face', unite: 'm²' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Étanchéité à l\'air', intitule: 'Test d\'infiltrométrie (Blower Door) — mesure n50, rapport Q4Pa', unite: 'ens' },
  { lot: 'Isolation thermique et acoustique', sousLot: 'Étanchéité à l\'air', intitule: 'Calfeutrement des traversées (réseaux, gaines) — mastic ou mousses', unite: 'ens' },

  // ── 13. Carrelage / Faïence ──────────────────────────────────────────────
  { lot: 'Carrelage / Faïence', sousLot: 'Préparation des supports', intitule: 'Ragréage fibré autolissant — rattrapage planéité, épaisseur 3 à 15 mm', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Préparation des supports', intitule: 'Étanchéité sous carrelage (SPEC) en zone humide — 2 couches croisées', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Préparation des supports', intitule: 'Natte de désolidarisation et d\'étanchéité sous carrelage (type Schlüter)', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Carrelage sol', intitule: 'Carrelage grès cérame 60×60 cm — collé à la colle C2S1, joints 3 mm', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Carrelage sol', intitule: 'Carrelage grès cérame grand format 80×80 cm — colle souple, joints 2 mm', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Carrelage sol', intitule: 'Carrelage extérieur antidérapant R11 30×30 cm — collé, joints époxy gris', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Carrelage sol', intitule: 'Carrelage imitation parquet 20×80 cm — rectifié, joint 1,5 mm invisible', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Carrelage sol', intitule: 'Carrelage marbre 60×60 — poli brillant, marbrerie posée au mortier-colle', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Faïence murale', intitule: 'Faïence murale 30×60 cm — collée sur enduit hydrofuge, joints 2 mm', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Faïence murale', intitule: 'Faïence mosaïque 5×5 cm — décor sur filet, collée colle S1, joints gris', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Faïence murale', intitule: 'Crédence cuisine faïence 10×20 cm — metro blanc, joint époxy ciment', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Plinthes et finitions', intitule: 'Plinthe carrelée assortie h=10 cm — posée collée sur mur', unite: 'ml' },
  { lot: 'Carrelage / Faïence', sousLot: 'Plinthes et finitions', intitule: 'Listello décoratif 5×30 cm — en faïence ou marbre, posé en frise', unite: 'ml' },
  { lot: 'Carrelage / Faïence', sousLot: 'Plinthes et finitions', intitule: 'Nez de marche en grès cérame antidérapant — profil arrondi, l=30 cm', unite: 'ml' },
  { lot: 'Carrelage / Faïence', sousLot: 'Plinthes et finitions', intitule: 'Joint de dilatation périphérique silicone — en pied de mur, largeur 8 mm', unite: 'ml' },
  { lot: 'Carrelage / Faïence', sousLot: 'Joints et accessoires', intitule: 'Rejointoiement époxy bicomposant — couleur au choix, résistant aux taches', unite: 'm²' },
  { lot: 'Carrelage / Faïence', sousLot: 'Joints et accessoires', intitule: 'Profil de jonction sol/mur aluminium — profil Schlüter Rondec', unite: 'ml' },
  { lot: 'Carrelage / Faïence', sousLot: 'Joints et accessoires', intitule: 'Profilé de seuil de porte aluminium — transition sol souple/carrelage', unite: 'u' },
  { lot: 'Carrelage / Faïence', sousLot: 'Joints et accessoires', intitule: 'Siphon de sol Ø90 mm inox brossé — grille 15×15 cm, pose encastrée', unite: 'u' },
  { lot: 'Carrelage / Faïence', sousLot: 'Terrasse carrelée', intitule: 'Carrelage terrasse sur plots réglables — dallettes 60×60, e=20 mm', unite: 'm²' },

  // ── 14. Revêtements de sol souples ───────────────────────────────────────
  { lot: 'Revêtements de sol souples', sousLot: 'Parquet', intitule: 'Parquet massif chêne 14×130 mm — pose collée, huilé blanc, finition brosse', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Parquet', intitule: 'Parquet contrecollé chêne 15×190 mm — pose flottante sur sous-couche', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Parquet', intitule: 'Parquet massif point de Hongrie — chêne 23×70 mm, posé collé, verni mat', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Parquet', intitule: 'Ragréage spécial parquet collé — humidimétrie < 3%, épaisseur ≤ 5 mm', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Parquet', intitule: 'Ponçage et vitrification parquet existant — 3 passes + vernis mat 2 couches', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Stratifié / Vinyle', intitule: 'Stratifié AC5 décor bois — pose flottante sur mousse 2 mm, jonctions', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Stratifié / Vinyle', intitule: 'LVT (Luxury Vinyl Tile) 4 mm — pose collée ou clipsée, décor bois ou pierre', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Stratifié / Vinyle', intitule: 'Sol vinyle rouleau homogène Taralay — 2 mm, soudé à chaud, couleur unie', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Stratifié / Vinyle', intitule: 'Dalles PVC autoadhésives 30×30 cm — pose à joints décalés, décor marbre', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Moquette', intitule: 'Moquette en lés bouclé 100% polyamide — collée, 50 oz/yd², résistance feu', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Moquette', intitule: 'Dalle moquette 50×50 cm — pose libre, changement à l\'unité, classe 33', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Liège / Caoutchouc', intitule: 'Sol liège comprimé 6 mm — pose collée, finition polyuréthane', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Liège / Caoutchouc', intitule: 'Sol caoutchouc Nora 3 mm — collé, antidérapant, résistance chimique', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Résine', intitule: 'Sol résine époxy autolissant 2 mm — primaire + résine + vernis, lisse', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Résine', intitule: 'Sol béton ciré 3 mm — sur chape existante, finition cire mat ou brillant', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Finitions et accessoires', intitule: 'Seuil de passage aluminium plat — transition de niveaux ≤ 5 mm', unite: 'u' },
  { lot: 'Revêtements de sol souples', sousLot: 'Finitions et accessoires', intitule: 'Plinthe assortie en MDF laqué ou bois — h=80 mm, posée collée', unite: 'ml' },
  { lot: 'Revêtements de sol souples', sousLot: 'Finitions et accessoires', intitule: 'Sous-couche acoustique 5 mm — ΔLw=19 dB, sous parquet flottant', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Finitions et accessoires', intitule: 'Dépose de l\'ancien revêtement (moquette, vinyle) + évacuation', unite: 'm²' },
  { lot: 'Revêtements de sol souples', sousLot: 'Finitions et accessoires', intitule: 'Protection provisoire du sol neuf pendant chantier — film PE 200 µm', unite: 'm²' },

  // ── 15. Peinture / Revêtements muraux ────────────────────────────────────
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Préparation des supports', intitule: 'Rebouchage fissures et trous — enduit de rebouchage + ponçage', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Préparation des supports', intitule: 'Impression pénétrante sur plaque BA13 — fixateur en phase aqueuse', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Préparation des supports', intitule: 'Ponçage et époussetage — finition Q4 sur enduit lissé', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Peinture intérieure', intitule: 'Peinture acrylique velours 2 couches sur murs — après impression', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Peinture intérieure', intitule: 'Peinture acrylique mate 2 couches sur plafonds — couleur blanc cassé', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Peinture intérieure', intitule: 'Peinture glycérophtalique satin sur boiseries — 3 couches, laquage fin', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Peinture intérieure', intitule: 'Peinture époxy bicomposant sur sol béton — 2 couches, antidérapant', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Peinture intérieure', intitule: 'Peinture anti-humidité en zone humide — 2 couches, fond + finition', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Peinture extérieure', intitule: 'Peinture façade siloxane 2 couches — sur enduit sain, couleur RAL', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Peinture extérieure', intitule: 'Lasure microporeuse 2 couches sur bardage bois — protection UV + eau', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Revêtements muraux', intitule: 'Toile de verre à peindre — 100 g/m², collée sur BA13, finition peinture', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Revêtements muraux', intitule: 'Papier peint non tissé intissé — collé sur mur préparé, raccords soignés', unite: 'rouleau' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Revêtements muraux', intitule: 'Béton ciré décoratif sur murs — 3 mm, finition cire naturelle', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Revêtements muraux', intitule: 'Enduit à la chaux aérienne — 2 passes, finition brossée ou lissée', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Revêtements muraux', intitule: 'Stuc vénitien — 3 couches + polissage, finition marbre', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Revêtements muraux', intitule: 'Habillage mural en lambris chêne huilé — 20×120 mm, pose encliquetée', unite: 'm²' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Finitions', intitule: 'Retouches peinture en fin de chantier — après pose équipements', unite: 'ens' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Finitions', intitule: 'Protection des surfaces non peintes pendant peinture — film + ruban', unite: 'ens' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Finitions', intitule: 'Nettoyage final après peinture — vitres, sols, interrupteurs', unite: 'ens' },
  { lot: 'Peinture / Revêtements muraux', sousLot: 'Finitions', intitule: 'Peinture de signalétique au sol — lignes, flèches, zones parking', unite: 'm²' },

  // ── 16. Plomberie / Sanitaires ───────────────────────────────────────────
  { lot: 'Plomberie / Sanitaires', sousLot: 'Alimentation eau froide/chaude', intitule: 'Canalisation multicouche PER-AL-PER Ø16 — sous gaine TPC corrugée', unite: 'ml' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Alimentation eau froide/chaude', intitule: 'Nourrice de distribution 6 départs en inox — avec vannes de sectionnement', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Alimentation eau froide/chaude', intitule: 'Colonne montante EF en cuivre Ø32 — pose apparente, supportage tous 2 m', unite: 'ml' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Alimentation eau froide/chaude', intitule: 'Adoucisseur d\'eau — capacité 20 L résine, by-pass, contrôle électronique', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Alimentation eau froide/chaude', intitule: 'Chauffe-eau thermodynamique 200 L — COP 3,5, installation et raccordement', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Évacuations', intitule: 'Canalisation PVC évacuation Ø40 — siphon lavabo, pente 3%', unite: 'ml' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Évacuations', intitule: 'Colonne chute EU/EV en PVC Ø100 — y compris raccords, piquages, fixations', unite: 'ml' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Évacuations', intitule: 'Siphon de sol Ø100 mm avec grille inox — pose encastrée, sortie horizontale', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Appareils sanitaires', intitule: 'WC suspendu avec bâti-support encastré — céramique blanche, abattant frein', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Appareils sanitaires', intitule: 'Lavabo céramique 60 cm — pose sur pied ou suspendu, robinetterie mitigeur', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Appareils sanitaires', intitule: 'Vasque à poser Ø420 mm — céramique ou pierre composite, robinetterie', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Appareils sanitaires', intitule: 'Baignoire acrylique 170×70 cm — bain tourbillon ou standard, tablier', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Appareils sanitaires', intitule: 'Douche italienne receveur extra-plat 90×90 cm — bonde Ø90, pare-douche verre', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Appareils sanitaires', intitule: 'Évier inox 2 bacs 120×50 cm — pose encastrée, bonde, siphon', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Robinetterie', intitule: 'Mitigeur lavabo monotrou — hauteur 200 mm, cartouche céramique, aérateur', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Robinetterie', intitule: 'Mitigeur thermostatique bain/douche — avec douchette, flexible 150 cm', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Robinetterie', intitule: 'Robinetterie cuisine mitigeur haut col de cygne — avec douchette extractible', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Équipements techniques', intitule: 'Surpresseur domestique — 1 bar-6 bar, groupe de sécurité, manomètre', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Équipements techniques', intitule: 'Vase d\'expansion 18 L — pour installation chauffage central', unite: 'u' },
  { lot: 'Plomberie / Sanitaires', sousLot: 'Équipements techniques', intitule: 'Test de pression réseaux — 1,5× pression de service, rapport contrôle', unite: 'ens' },

  // ── 17. Chauffage / Ventilation / Climatisation ───────────────────────────
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Chauffage', intitule: 'Chaudière gaz à condensation — puissance 24 kW, classe ErP A, installée', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Chauffage', intitule: 'PAC air/eau — puissance 12 kW, COP 4,5, installation complète', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Chauffage', intitule: 'Poêle à granulés — puissance 8 kW, réservoir 25 kg, thermostat', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Chauffage', intitule: 'Radiateur acier panneau type 22 — 1000×600 mm, robinet thermostatique', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Chauffage', intitule: 'Plancher chauffant hydraulique — tube PER Ø16, dalle, régulation', unite: 'm²' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Chauffage', intitule: 'Collecteur de distribution chauffage 6 départs — vanne d\'équilibrage', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Chauffage', intitule: 'Réseau de distribution chauffage en cuivre Ø22 — calorifugé', unite: 'ml' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Chauffage', intitule: 'Régulation thermostat programmable connecté — Netatmo ou équivalent', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Ventilation', intitule: 'VMC hygroréglable type B — caisson, bouches autorégulables, extraction', unite: 'ens' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Ventilation', intitule: 'VMC double flux — rendement 90%, by-pass, filtre F7, installation complète', unite: 'ens' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Ventilation', intitule: 'Gaine circulaire spiralée Ø160 — galvanisée, isolation 25 mm, raccords', unite: 'ml' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Ventilation', intitule: 'Bouche d\'extraction hygroréglable — réglage 15 à 60 m³/h', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Ventilation', intitule: 'Bouche soufflage basse vitesse — circulaire Ø160, déflecteurs réglables', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Climatisation', intitule: 'Climatiseur split mural 2,5 kW — A+++, réversible, pompe à chaleur', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Climatisation', intitule: 'Groupe condenseur extérieur — pour 2 unités intérieures, R32', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Climatisation', intitule: 'Unité intérieure cassette de plafond 4 voies — 5 kW, avec commande', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Climatisation', intitule: 'Liaisons frigorifiques en cuivre gaîné — Ø6,35+12,7 mm, isolation', unite: 'ml' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Climatisation', intitule: 'CTA (Centrale Traitement Air) — 2 000 m³/h, filtrasse G4+F7, chauffage', unite: 'u' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Énergies renouvelables', intitule: 'Capteurs solaires thermiques — 4 m², installation ECS, ballon 300 L', unite: 'ens' },
  { lot: 'Chauffage / Ventilation / Climatisation (CVC)', sousLot: 'Énergies renouvelables', intitule: 'Équilibrage et mise en service installation CVC — réglage débits, mesures', unite: 'ens' },

  // ── 18. Électricité CFO/CFA ───────────────────────────────────────────────
  { lot: 'Électricité CFO/CFA', sousLot: 'Distribution générale', intitule: 'Tableau électrique général — coffret 36 modules, disjoncteur différentiels 30 mA', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Distribution générale', intitule: 'Câblage réseau de distribution — câble U1000R2V 5G6 mm² sous tube IRL', unite: 'ml' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Distribution générale', intitule: 'Tableau divisionnaire logement — 13 modules avec DDR 30 mA', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Distribution générale', intitule: 'Mise à la terre — piquet Ø2 m + réseau maillé, liaison équipotentielle', unite: 'ens' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Prises et éclairage', intitule: 'Prise de courant 2P+T 16A encastrée — série NF, avec plaque', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Prises et éclairage', intitule: 'Prise USB A+C encastrée — intégrée dans plaque double', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Prises et éclairage', intitule: 'Interrupteur va-et-vient — encastré, série NF, avec plaque assortie', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Prises et éclairage', intitule: 'Détecteur de mouvement — infrarouge passif, portée 8 m, temporisation', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Prises et éclairage', intitule: 'Luminaire LED encastré plafond — 10 W, 3000 K, variateur compatible', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Prises et éclairage', intitule: 'Lustre suspension — alimentation sur rosace plafond, câble textile', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Prises et éclairage', intitule: 'Éclairage extérieur — applique façade IP65, LED 15 W, détecteur intégré', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Courants faibles / CFA', intitule: 'Tableau de communication — baie 9U, répartiteur fibre + RJ45', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Courants faibles / CFA', intitule: 'Prise RJ45 cat.6A — encastrée, blindée, connecteur fiche + cordon', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Courants faibles / CFA', intitule: 'Câblage informatique cat.6A FTP — tiroir de brassage, tests atténuation', unite: 'ml' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Courants faibles / CFA', intitule: 'Alarme intrusion Grade 2 — centrale, détecteurs PIR, claviers, sirène', unite: 'ens' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Courants faibles / CFA', intitule: 'Vidéophonie — platine extérieure avec caméra, moniteur intérieur 7"', unite: 'ens' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Courants faibles / CFA', intitule: 'Système de contrôle d\'accès — lecteur badge RFID, centrale, porte sécurisée', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Domotique / Éclairage scénique', intitule: 'Système domotique KNX — 8 zones, télécommande, programmation scènes', unite: 'ens' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Domotique / Éclairage scénique', intitule: 'Variateur LED encastré — compatible LED et DALI, 400 W, avec neutre', unite: 'u' },
  { lot: 'Électricité CFO/CFA', sousLot: 'Énergies renouvelables', intitule: 'Panneaux photovoltaïques 400 Wc — 10 panneaux + onduleur + coffret AC/DC', unite: 'ens' },

  // ── 19. Ascenseurs / Équipements techniques ──────────────────────────────
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Ascenseur', intitule: 'Ascenseur électrique 630 kg — 8 personnes, 4 niveaux, cabine inox', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Ascenseur', intitule: 'Ascenseur hydraulique 450 kg — sans local machine, 3 niveaux', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Ascenseur', intitule: 'Monte-charge 1 000 kg — 2 niveaux, porte à rideau, téléalarme', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Ascenseur', intitule: 'Plateforme élévatrice PMR — 400 kg, course 3 m, portillon sécurité', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Ascenseur', intitule: 'Cabine ascenseur — finition inox brossé, miroir, main courante, éclairage LED', unite: 'ens' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Sécurité incendie', intitule: 'Centrale SSI de catégorie A — détecteur automatique incendie réseau', unite: 'ens' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Sécurité incendie', intitule: 'Détecteur optique de fumée adressable — avec socle, conforme EN 54-7', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Sécurité incendie', intitule: 'Déclencheur manuel (boîtier brise-glace) — rouge, NF EN 54-11', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Sécurité incendie', intitule: 'Diffuseur sonore / lumineux — signal d\'alarme 85 dB à 1 m, adressable', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Sécurité incendie', intitule: 'Extincteur eau pulvérisée 6 L — classe A, norme EN 3, avec support mural', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Sécurité incendie', intitule: 'Robinet incendie armé Ø19 mm — coffret 60×60, 20 ml tuyau semi-rigide', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Sécurité incendie', intitule: 'Dispositif d\'asservissement — arrêt CTA, déverrouillage portes coupe-feu', unite: 'ens' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'GTC / Supervision', intitule: 'Système GTB/GTC — automate BACnet, 50 points, supervision web', unite: 'ens' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'GTC / Supervision', intitule: 'Compteurs d\'énergie communicants — électricité, gaz, eau, relevé à distance', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Équipements spéciaux', intitule: 'Groupe électrogène 50 kVA — diesel, ATS, capot insonorisé, fondation', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Équipements spéciaux', intitule: 'UPS onduleur 10 kVA — autonomie 30 min, batterie Li-Ion, baie 19"', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Équipements spéciaux', intitule: 'Borne de recharge IRVE 7,4 kW — mode 3, câble T2, RFID, conforme déc. IRVE', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Équipements spéciaux', intitule: 'Porte automatique coulissante — 2 vantaux, capteur radar, EU 2016/425', unite: 'u' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Maintenance préventive', intitule: 'Contrat de maintenance ascenseur — vérifications réglementaires + carnet', unite: 'an' },
  { lot: 'Ascenseurs / Équipements techniques', sousLot: 'Maintenance préventive', intitule: 'Vérification réglementaire installation électrique — rapport consuel/CONSULT', unite: 'ens' },

  // ── 20. Espaces verts / Aménagements extérieurs ───────────────────────────
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Préparation et terrassement', intitule: 'Décapage et dépôt de terre végétale — épaisseur 30 cm', unite: 'm²' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Préparation et terrassement', intitule: 'Apport et étalement de terre végétale améliorée — 20 cm compacté', unite: 'm²' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Préparation et terrassement', intitule: 'Amendement du sol — compost 5 kg/m² + chaux dolomitique si nécessaire', unite: 'm²' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Plantations', intitule: 'Gazon par semis — prairie fleurie ou gazon sport, semis + premier tonte', unite: 'm²' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Plantations', intitule: 'Gazon en rouleaux prêt à poser — qualité sport, plaquage sur sol préparé', unite: 'm²' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Plantations', intitule: 'Plantation d\'arbres tiges en fosse — circonférence 14/16, tuteur bois', unite: 'u' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Plantations', intitule: 'Plantation d\'arbustes en massif — 3 litres, paillage BRF 10 cm', unite: 'u' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Plantations', intitule: 'Haie vive — ligustrum ou photinia, plants 60/80 cm, rangée double', unite: 'ml' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Plantations', intitule: 'Couvre-sol vivaces — godets 9 cm, densité 9/m², paillage compris', unite: 'm²' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Allées et cheminements', intitule: 'Allée gravillonnée stabilisée — concassé calcaire 10/14, e=10 cm, bordure', unite: 'm²' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Allées et cheminements', intitule: 'Dalle béton désactivé — e=12 cm, armé, finition granulats apparents', unite: 'm²' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Allées et cheminements', intitule: 'Pavés autobloquants béton 20×10×6 cm — pose sur lit de sable 5 cm, joints', unite: 'm²' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Allées et cheminements', intitule: 'Terrasse bois composite — lames 23×138 mm, structure alu, visserie inox', unite: 'm²' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Clôtures et mobilier', intitule: 'Clôture bois occultant — lames verticales 19×90 mm, poteaux 90×90 cm béton', unite: 'ml' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Clôtures et mobilier', intitule: 'Mur de soutènement en gabions — paniers 1000×500×500 mm, remplissage galets', unite: 'm²' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Clôtures et mobilier', intitule: 'Pergola bois traité CL3 — poteaux 12×12 cm, poutres 8×16, lasure', unite: 'ens' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Arrosage et éclairage', intitule: 'Réseau arrosage automatique — électrovanne, gicleurs escamotables, programmateur', unite: 'ens' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Arrosage et éclairage', intitule: 'Éclairage extérieur à LED — borne 60 cm, câble enfoui, programmateur', unite: 'u' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Arrosage et éclairage', intitule: 'Cuve récupération eau de pluie 5 000 L — enterrée, pompe, trop-plein', unite: 'u' },
  { lot: 'Espaces verts / Aménagements extérieurs', sousLot: 'Entretien 1ère année', intitule: 'Entretien espaces verts première année — tonte, taille, reprise des manquants', unite: 'an' },

  // ── 21. Démolition / Déconstruction ─────────────────────────────────────
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Dépose et déconnexion réseaux', intitule: 'Déconnexion et purge réseaux avant démolition — fluides, gaz, électricité', unite: 'ens' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Dépose et déconnexion réseaux', intitule: 'Dépose robinetterie et appareils sanitaires existants', unite: 'u' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Dépose et déconnexion réseaux', intitule: 'Dépose du tableau électrique et appareillages — avec neutralisation', unite: 'ens' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Démolition gros œuvre', intitule: 'Démolition de cloisons en maçonnerie — briques ou parpaings, évacuation', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Démolition gros œuvre', intitule: 'Démolition de cloisons en plaques de plâtre — ossature + plaques', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Démolition gros œuvre', intitule: 'Démolition de chape béton existante — épaisseur jusqu\'à 10 cm, brise-béton', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Démolition gros œuvre', intitule: 'Démolition voile béton armé — découpage disque diamant, blindage si nécessaire', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Démolition gros œuvre', intitule: 'Ouverture de trémie dans plancher béton — Ø ou surface au m², renfort IPN', unite: 'u' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Démolition gros œuvre', intitule: 'Démolition plancher à corps creux — hourdis + dalle, jusqu\'à 25 cm', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Dépose couverture / charpente', intitule: 'Dépose couverture tuiles ou ardoises — tri sélectif, palettisation', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Dépose couverture / charpente', intitule: 'Dépose charpente bois — tri bois sain / bois traité, selon diagnostics', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Dépose couverture / charpente', intitule: 'Dépose menuiseries extérieures — fenêtres, portes, volets, bâtis', unite: 'u' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Dépose revêtements', intitule: 'Dépose carrelage sol avec ragréage — y compris colle, jusqu\'à 5 mm', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Dépose revêtements', intitule: 'Dépose revêtement de sol souple (moquette, PVC, parquet collé)', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Dépose revêtements', intitule: 'Piquage d\'enduits muraux ou faïences existants', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Gestion des déchets', intitule: 'Location benne 8 m³ — pour gravats et matériaux inertes', unite: 'sem' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Gestion des déchets', intitule: 'Évacuation et traitement déchets inertes — pesée en décharge agréée', unite: 't' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Gestion des déchets', intitule: 'Diagnostic amiante avant travaux — repérage SS3, rapport certifié', unite: 'ens' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Gestion des déchets', intitule: 'Désamiantage — dépose matériaux amiantés, confinement, évacuation filière', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Gestion des déchets', intitule: 'Diagnostic plomb (CREP) — rapport avant démolition ou réhabilitation', unite: 'ens' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Gestion des déchets', intitule: 'Protection et bâchage des parties conservées — film PE + panneaux OSB', unite: 'm²' },
  { lot: 'Démolition / Déconstruction (si réhabilitation)', sousLot: 'Gestion des déchets', intitule: 'Etaiement provisoire des ouvrages porteurs — avant ouverture ou démolition', unite: 'ens' },
]

async function main() {
  console.log(`🌱 Démarrage seed bibliothèque — ${items.length} postes sur 21 lots`)

  const result = await prisma.libraryItem.createMany({
    data: items.map((item) => ({
      lot: item.lot,
      sousLot: item.sousLot ?? null,
      intitule: item.intitule,
      unite: item.unite ?? null,
      source: SOURCE,
      validated: true,
      usageCount: 0,
    })),
    skipDuplicates: false,
  })

  console.log(`✅ ${result.count} postes insérés avec succès.`)

  // Résumé par lot
  const byLot: Record<string, number> = {}
  for (const item of items) {
    byLot[item.lot] = (byLot[item.lot] ?? 0) + 1
  }
  for (const [lot, count] of Object.entries(byLot)) {
    console.log(`   • ${lot} : ${count} postes`)
  }
}

main()
  .catch((e) => {
    console.error('❌ Erreur seed bibliothèque:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
